- doc/manual/network.rst
In order to change the jackport I figured to use:
```<request><source id="42" port="system:capture_3"/></request>```
Instead of:
```<request><source id="42" port_name="system:capture_3"/></request>```
> change source port xml request revised

- pd/ssrclient.pd_lua
https://groups.google.com/forum/#!msg/soundscaperenderer/Ndfl9kCQCqk/zpIrimHaBwAJ
> Pd/Lua client: avoid unpack(), use table.concat()

- src/gui/quserinterface.cpp
The key "s" did not toggle the solo state, as you would expect it when hitting "s" multiple times. Very inconvenient.
In order to unmute you have to unselect all sources first and then hit "s" again. This clears the previous solo list and you would have to select all sources to solo again.
The key "m" already shows the expected behavior for mute (toggle) state.
- This PR improves the shortcut "s" and matches it to shortcut "m"
> Toggle solo state by key "s"

- doc/manual/operation.rst
See https://github.com/SoundScapeRenderer/ssr/issues/83
> Add macOS quarantine solution

- apf/apf/mimoprocessor.h
- src/binauralrenderer.h
- src/configuration.cpp
- src/rendererbase.h
These commits improve on code that g++ deduced as intended, but other compilers might not (in this case MSVC).
> Improvements for more explicit code

- configure.ac
> Change libasio -> Asio in configure message

- man/Makefile.am
This is a continuation of #55.
> make help2man locale configurable

- configure.ac
> Unconditionally add -pthread for GCC

- src/razor-ahrs/RazorAHRS.cpp
- src/razor-ahrs/RazorAHRS.h
- src/trackerintersense.cpp
- src/trackerintersense.h
- src/trackerpolhemus.cpp
- src/trackerpolhemus.h
- src/trackervrpn.cpp
- src/trackervrpn.h
Switching from pthreads to std::threads. With that the SSR itself is now completely on std::threads.
> Replace pthreads by std::threads and unify layout

- src/aaprenderer.h
- src/binauralrenderer.h
- src/brsrenderer.h
- src/dcarenderer.h
- src/rendererbase.h
- src/rendersubscriber.h
- src/vbaprenderer.h
- src/wfsrenderer.h
Ideally, this shouldn't change the current behavior.
> Extend renderer API to 3D (but not the renderers themselves!)

- src/aaprenderer.h
- src/audioplayer.cpp
- src/audiorecorder.cpp
- src/configuration.cpp
- src/controller.h
- src/gui/qopenglplotter.cpp
- src/gui/quserinterface.cpp
- src/legacy_network/commandparser.cpp
- src/legacy_network/networksubscriber.cpp
- src/legacy_network/server.cpp
- src/legacy_scene.cpp
- src/legacy_scene.h
- src/loudspeakerrenderer.h
- src/maptools.h
- src/razor-ahrs/RazorAHRS.cpp
- src/rendersubscriber.h
- src/scene.h
- src/ssr_global.h
- src/trackerintersense.cpp
- src/trackerpolhemus.cpp
- src/trackerrazor.cpp
- src/trackerrazor.h
- src/trackervrpn.cpp
- src/websocket/connection.h
- src/websocket/server.h
- src/wfsrenderer.h
Fixes https://github.com/SoundScapeRenderer/ssr/issues/133
> Rename global defines

- ci/build-deps.sh
I was hoping there are no interactions between #149 and #150, but there were ...
This PR tries to fix this.
> TST: Copy Intersense files after compiling VRPN (on Travis)

- apf/apf/jackclient.h
- src/binauralrenderer.h
- src/brsrenderer.h
- src/controller.h
- src/genericrenderer.h
- src/rendererbase.h
- src/wfsrenderer.h
A few hopefully harmless commits before some more major changes regarding dynamic audio scenes.
> Miscellaneous changes

- src/ssr_aap.cpp
- src/ssr_binaural.cpp
- src/ssr_brs.cpp
- src/ssr_dca.cpp
- src/ssr_main.h
- src/ssr_vbap.cpp
- src/ssr_wfs.cpp
> Generic main function (with exception handling)

- src/legacy_network/networksubscriber.cpp
- src/legacy_network/networksubscriber.h
- src/xmlparser.cpp
- src/xmlparser.h
> IP Interface: send source name

- mex/Makefile
- mex/ssr_mex.h
... it still only supports 2D.
> Update MEX code

- .travis.yml
https://github.com/Homebrew/brew/issues/5068
> Travis-CI: Use LIBXML_CFLAGS

- browser-gui/src/index.js
- browser-gui/src/sceneviewer.js
- browser-gui/src/style.css
> Browser-GUI: Add controls for reference position/orientation

- browser-gui/src/sceneviewer.js
To try it out:
* start the SSR (with the WebSocket feature enabled)
* open https://33-216861629-gh.circle-artifacts.com/0/browser-gui/index.html in your browser
> Browser-GUI: Source can be selected, moved and rotated

- .circleci/config.yml
... in order to be able to create man-pages for the tarball.
> CircleCI: Install help2man

- browser-gui/yarn.lock
... to take care of https://github.com/advisories/GHSA-h9rv-jmmf-4pgx
> Yarn upgrade

- doc/manual/conf.py
- doc/manual/installation.rst
- doc/manual/issues.rst
https://122-216861629-gh.circle-artifacts.com/0/manual/issues.html
> DOC: Some changes to "Issues" section

- ci/build-deps.sh
See https://github.com/zaphoyd/websocketpp/issues/794
> Travis-CI: Use "develop" branch of Websocket++

- doc/manual/.editorconfig
- doc/manual/index.rst
- doc/manual/network-fudi.rst
- doc/manual/network-legacy.rst
- doc/manual/network-websocket.rst
- doc/manual/network.rst
This is some minimal content for getting started.
More details should be added later.
Rendered: https://129-216861629-gh.circle-artifacts.com/0/manual/network.html
> DOC: Add pages for all network interfaces

- doc/manual/index.rst
Rendered: https://ssr--213.org.readthedocs.build/en/213/
> DOC: add introductory paragraph and a few links to user manual

- browser-gui/yarn.lock
to avoid vulnerability in node-forge
> Browser GUI: yarn upgrade

- doc/manual/index.rst
- doc/manual/network-fudi.rst
- doc/manual/ssr-as-library.rst
Rendered: https://260-216861629-gh.circle-artifacts.com/0/manual/ssr-as-library.html
> DOC: add page about using the SSR as library

- .github/workflows/main.yml
While I'm at it, I've also installed the necessary Perl module to make `help2man` work on macOS.
> CI: Simplify handling of package lists

- doc/manual/installation.rst
Rendered: https://ssr--224.org.readthedocs.build/en/224/installation.html
> DOC: minor changes to "installation" page

- .github/workflows/main.yml
- ci/build-deps-macos.sh
- ci/build-deps-ubuntu.sh
- doc/manual/building-from-source.rst
- doc/manual/index.rst
- doc/manual/installation.rst
- doc/manual/issues.rst
- doc/manual/operation.rst
Rendered:
* https://ssr--226.org.readthedocs.build/en/226/installation.html
* https://ssr--226.org.readthedocs.build/en/226/building-from-source.html
> DOC: Updates to the "installation" and "building from source" pages

- doc/manual/building-from-source.rst
Rendered: https://ssr--228.org.readthedocs.build/en/228/building-from-source.html#git-repository
> DOC: mention Git submodules

- doc/manual/building-from-source.rst
Rendered: https://ssr--229.org.readthedocs.build/en/229/building-from-source.html#dependencies
> DOC: refer to ci script for websocketpp/libmysofa building instructions

- .github/workflows/main.yml
See https://github.com/google/filament/issues/2146.
> CI: add -fno-builtin for Clang 9

- doc/manual/operation.rst
Rendered: https://ssr--236.org.readthedocs.build/en/236/operation.html
> User manual: Some updates to the "operation" section

- data/websocket_resources/ssr-test-client.html
- doc/manual/browser-gui.rst
- doc/manual/index.rst
- doc/manual/network-websocket.rst
- src/websocket/server.h
Rendered: https://ssr--243.org.readthedocs.build/en/243/browser-gui.html
> Browser GUI: simplify server routes, add documentation to the manual

- .circleci/config.yml
See https://github.com/dante-ev/docker-texlive/issues/37.
> CircleCI: Install pip

- browser-gui/README.md
- browser-gui/package.json
- browser-gui/src/sceneviewer.js
- browser-gui/webpack.config.js
- browser-gui/yarn.lock
> Browser-GUI: update to latest threejs version

- flext/Makefile
- flext/ssr_brs~.cpp
- flext/ssr_flext.h
> Pd externals: make paths relative to patch directory 

- .circleci/config.yml
- doc/manual/installation.rst
- doc/manual/operation.rst
- doc/manual/renderers.rst
The original link doesn't work anymore.
> Provide CIPIC link from archive.org

- browser-gui/Makefile.am
- configure.ac
- src/Makefile.am
This should fix (some of) the problems mentioned in #293.
> build system: allow paths with spaces

- .github/workflows/main.yml
- .github/workflows/pd-externals.yml
#297 failed, time for a CI upgrade.
> CI version upgrade

- ci/build-small-libsndfile.sh
That's not really important, but I just stumbled upon it, so why not upgrade?
> CI: use libsndfile 1.1.0

- .github/workflows/main.yml
- .github/workflows/pd-externals.yml
A bit of housekeeping ...
This also includes #305.
> CI upgrade

- .github/workflows/main.yml
- ci/build-deps-macos.sh
- doc/manual/building-from-source.rst
... and I guess we also don't need static libs here.
> CI: build libmysofa without tests

- browser-gui/package.json
- browser-gui/yarn.lock
#326 wasn't aggressive enough, now I've manually updated all NPM packages.
> Manually update NPM packages to the latest versions

- src/websocket/server.h
> WebSocket server: serve 404 page

- .circleci/config.yml
The `danteev` image doesn't seem to be maintained anymore.
> CircleCI: use texlive image

- doc/manual/building-from-source.rst
This is a continuation of #347.
I have left only the package names for Debian/Ubuntu.
> DOC: update Linux dependencies

- data/websocket_resources/ssr-test-client.html
- src/api.h
- src/controller.h
- src/fudi/subscriber.h
- src/gui/quserinterface.cpp
- src/legacy_scene.h
- src/rendersubscriber.h
- src/websocket/connection.h
This helps keeping orientation if more than one SSR instance is running.
> Add JACK client name to window title

- doc/manual/operation.rst
- pd/supperware_head_tracker_to_ssr.pd
... at least indirectly through a Pd patch.
> Add supperware head tracker support

- src/gui/qopenglplotter.cpp
- src/gui/quserinterface.cpp
Reference position and rotation and reference offset position and rotation are now properly displayed in the GUI with all renderers.
> GUI: display reference and reference offset

- .github/workflows/main.yml
> CI: remove unsupported Xcode version

- doc/manual/operation.rst
This is the CircleCI pipeline which checks the links: https://app.circleci.com/pipelines/github/mgeier/ssr/800/workflows/e6be20a6-8f7b-4293-95e8-d122aa9449df/jobs/851
> DOC: use https in Ardour link

- .github/workflows/main.yml
- .github/workflows/pd-externals.yml
"upload" and "download" must be updated at the same time.
> Combine dependabot fixes
