- configure.ac
- man/Makefile.am
help2man is missing, compiling aborts. Installing fixes it. Tested on Ubuntu 14.04 and 15.10.
> help2man dependency for ubuntu

- src/wfsrenderer.h
Sources in WFS won’t play at all if it is initialized exactly at the
reference point. This checks whether _rhs_ (distance between source and
ref_point) == 0 and simply sets _rhs_ to be  -0.001 (effectively moving the source 0.001 in the positive y direction).
> Fix centered WFS source

- data/MacOSX/Makefile.am
- adds -f to both cp (ecasound and qt_menu.nib) to not fail if the file already exists
- sets the necessary -w permission on the copied qt frameworks so install_name_tool can do it's thing
> Fix OSX build process

- configure.ac
Before that, this nonsensical message was displayed:
```
checking Searching for non-default libecasoundc include directory...
```
> Build System: Fix message for checking ecasound include path

- src/gui/qopenglplotter.cpp
Darkening the color of muted sources.
This makes it so much easier to recognize whether sources are in mute state.
> Darker muted sources

- apf/apf/cxx_thread_policy.h
This was removed from the rest of the code base in commit b50218f59ed379ad3645a04bdb37fd72475f5ff4.
Closes #91.
> Remove compile-time check for _REENTRANT in cxx_thread_policy.h

- apf/apf/commandqueue.h
- data/MacOSX/dylibbundler/src/Utils.cpp
- src/audioplayer.cpp
- src/audiorecorder.cpp
- src/configuration.cpp
- src/razor-ahrs/RazorAHRS.cpp
- src/trackerintersense.cpp
- src/trackerpolhemus.cpp
sleep() and usleep() are obsolete posix specific implementations and should be replaced by the c++11 standard library.  
It's also specific about the time unit and we get rid of a lot `#include <unistd.h>`.
> Replace sleep() and usleep() by c++11

- src/brsrenderer.h
Incorporates the reference_offset for the BRIR rendering.
tested with
```
echo -e '<request><reference_offset><orientation azimuth="0"/></reference_offset></request>\0' | nc localhost 4711
```
> add reference offset orientation for BRS Renderer

- doc/manual/operation.rst
- doc/manual/renderers.rst
There is still one broken link left:
https://dl.dropboxusercontent.com/u/28869550/JackOSX.0.92_b3.zip
What is the current recommendation for JACK on macOS?
Can somebody please update those instructions?
BTW, the links can be automatically checked by switching to the directory `doc/manual` and running
make linkcheck
Should we also include this in our Travis-CI config?
> DOC: Fix a few broken links

- configure.ac
Be a bit more explicit about libasio being necessary for the IP interface (and avoid confusion with the Windows audio interface).
> make the meaning of asio.hpp self-explanatory

- src/nfchoarenderer.h
> NFC-HOA Renderer: switch from FFT to IFFT

- Makefile.am
- apf/performance_tests/biquad_count_denormals.cpp
- apf/performance_tests/biquad_denormals.cpp
- configure.ac
- data/MacOSX/run-ssr.applescript
- data/ssr
- doc/manual/operation.rst
- doc/manual/renderers.rst
- flext/Makefile
- flext/README.md
- flext/ssr_dca.cpp
- flext/ssr_dca~-help.pd
- flext/virtual_dca.pd
- mex/Makefile
- mex/README.md
- mex/ssr_dca.cpp
- mex/ssr_helper.m
- src/Makefile.am
- src/dcacoefficients.h
- src/dcarenderer.h
- src/ssr_dca.cpp
The file names still use NFC-HOA, but all user interface related terms have been updated.
This excludes the flext and mex parts for now. The objects are still use NFC-HOA here, too.
> Change name NFC-HOA to DCA and update manual

- .travis.yml
- ci/install-deps.sh
... in the hope of passing CI in #127.
Does anyone need support for lower versions?
> TST: Update GCC, clang and Xcode versions on Travis-CI

- .travis.yml
- ci/install-deps.sh
Also:
* Remove xcode9.4 build from Travis-CI
... because it doesn't support std::optional
* Remove clang 5 (testing 2 versions seems sufficient)
> TST: Upgrade to Ubuntu Xenial on Travis-CI

- doc/manual/gui.rst
- src/gui/qopenglplotter.cpp
- src/gui/qopenglplotter.h
- src/gui/quserinterface.cpp
- src/gui/quserinterface.h
This enables drag & drop for audio files and scene files into the GUI. This can be handy for quick testing of something. I also changed the signature of the function `load_scene` in ```controller.h```:
https://github.com/SoundScapeRenderer/ssr/commit/74a356aea93bf354923c2b6e765015ec3dc7674b#diff-1f84d7860b51690b2964fd6241a307aaR131
One can now "add" a scene or audio file to an existing one. This can also be handy if one wants to quickly populate a scene without having to write an asd-file.
Questions are:
1) This change of the signature of `load_scene` back propagates into `publisher.h`: https://github.com/SoundScapeRenderer/ssr/commit/74a356aea93bf354923c2b6e765015ec3dc7674b#diff-7fc5376aafac5f57d0519684ea647e06R61
Does this cause any issues?
2) Adding of a scene is enabled by holding the …
> Drag and drop

- browser-gui/yarn.lock
... in order to avoid Github's warning about CVE-2019-10744 concerning `lodash`:
Vulnerable versions: < 4.17.13
Patched version: 4.17.13
Affected versions of lodash are vulnerable to Prototype Pollution.
The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.
> yarn upgrade

- data/websocket_resources/ssr-test-client.html
- src/api.h
- src/controller.h
- src/legacy_network/networksubscriber.cpp
- src/legacy_network/networksubscriber.h
- src/legacy_scene.h
- src/legacy_source.h
- src/rendererbase.h
- src/rendersubscriber.h
- src/scene.h
- src/websocket/connection.h
Currently, this feature is not used yet.
But it will be used by a future PR about dynamic sources.
The browser client changes the visibility of sources according to their "active" state (this was already implemented before).
The legacy Qt GUI ignores the property for now (inactive sources are shown the same way as active sources).
> Allow sources to be activated/deactivated

- src/websocket/connection.h
I have been reading the source code of ssr recently. I found a small code defect in websocket interface part. And I just added a simple type check to fix it.
> add a small type check in command `mod-src` of websocket interface

- .travis.yml
- apf/apf/mimoprocessor.h
- ci/build-deps.sh
- configure.ac
- src/binauralrenderer.h
This uses https://github.com/hoene/libmysofa for loading SOFA files.
Currently, this only works when using a single audio thread (e.g. using the command-line option `--threads=1`).
I hope to find a quick solution to enable multiple threads, see also https://github.com/hoene/libmysofa/issues/80.
SOFA files with delays are not supported. I think it would be quite a lot of work to implement this. But maybe I'm wrong. Anyway, I'm not planning to implement this soon.
The interpolation feature of `libmysofa` (and the "neighborhood" search used for that) is currently not used. I'm not planning to add this in this PR, but we might add it later.
> Add SOFA support to binaural renderer

- .travis.yml
This way, contributors can enable Travis-CI on their fork and have CI on their branches before creating a PR on the main repo.
> Travis-CI: run on all branches

- browser-gui/src/index.js
- browser-gui/src/sceneviewer.js
- browser-gui/src/style.css
In addition to the previous "3D" view, this adds a "top" view (using an orthographic camera, kinda like the legacy Qt GUI) and an "ego" view (that moves with the reference [+ reference offset]).
The new cameras don't have "controls" yet, i.e. panning, zooming etc. with the mouse is not possible.
> Browser-GUI: Add two more camera views

- src/gui/qopenglplotter.cpp
There was an issue with how the source ids were handled inside the GUI.
> Fix GUI bug that causes seg. fault when moving sources

- src/Makefile.am
- src/controller.h
- src/geometry.h
This did work fine for 2D, but in 3D situations this caused somewhat erratic rotations.
Now the *up* vector `(0, 0, 1)` is taken into account and everything should be fine.
> Fix auto-rotation for the 3D case

- .circleci/config.yml
- .travis.yml
Move "make distcheck" from Travis-CI to CircleCI.
This is the generated tarball: https://49-216861629-gh.circle-artifacts.com/0/ssr-0.5.0-100-g99fb884.tar.gz
I found a strange problem when downloading this file with Firefox 70/Linux: The file is double gzipped.
This is probably related to https://bugzilla.mozilla.org/show_bug.cgi?id=610679.
Anyway, it is fine when e.g. downloaded by Chromium.
> CircleCI: Create tarball

- doc/manual/gui.rst
- src/gui/quserinterface.cpp
This enables 'solo in place' functionality.
Very handy to quickly compare two tracks.
> Add 'solo in place'

- .circleci/config.yml
- browser-gui/Makefile.am
- browser-gui/README.md
- browser-gui/package.json
- browser-gui/webpack.config.js
- browser-gui/yarn.lock
- configure.ac
- data/Makefile.am
This is the generated tarball: https://63-216861629-gh.circle-artifacts.com/0/ssr-0.5.0-105-ge87d035.tar.gz
It contains these auto-generated files:
* the PDF manual in `doc/`
* the man pages in `man/`
* the browser GUI files in `data/websocket_resources/`
Firefox users please note #183 before downloading the tarball.
> Include browser GUI files in the tarball

- src/api.h
- src/controller.h
- src/websocket/connection.h
JACK's CPU usage estimation typically stays the same for multiple audio blocks. Now it is only sent when it actually changes.
When the JACK transport is stopped, the frame number (which is always the same) is now not sent repeatedly anymore.
Finally, the accuracy of numbers sent via WebSocket is limited to 5 places in order to avoid sending useless data.
> Send fewer CPU and transport frame events

- .github/workflows/main.yml
CI failed in https://github.com/SoundScapeRenderer/ssr/actions/runs/273991733.
This might be a temporary glitch, because this has worked before rebase-merging #215.
If the problem doesn't go away on its own in a few days, we should consider merging this PR.
> CI: Disable Xcode 10.3

- .circleci/config.yml
- .readthedocs.yml
- doc/manual/conf.py
- doc/manual/requirements.txt
I didn't like the RTD theme, so I've created my own ...
I've also enable a little Sphinx extension that I've written that shows the last-changed date (based on Git) on each page.
Rendered: https://ssr--227.org.readthedocs.build/en/227/
> DOC: switch HTML manual to "insipid" theme

- configure.ac
Alternative to #248.
This has the added benefit that the version requirement can be specified.
> Use pkg-config to check for libfmt

- .circleci/config.yml
- doc/manual/conf.py
- doc/manual/installation.rst
- doc/manual/renderers.rst
status page: https://app.circleci.com/pipelines/github/mgeier/ssr/307/workflows/3e65d625-d4f6-4b1f-b6bd-2c1c33db7d06/jobs/309
The link https://dev.qu.tu-berlin.de/projects/measurements/wiki/Impulse_Response_Measurements (for the Sputnik BRIRs) is currently broken!
> CircleCI: enable linkcheck builder

- src/controller.h
Since #230, the GUI crashed on shutdown with a backtrace that looked something like this:
```
frame #0: 0x000000010911b6b5 QtCore`QReadWriteLock::tryLockForWrite(int) + 21
frame #1: 0x00000001084e4caa QtOpenGL`___lldb_unnamed_symbol45$$QtOpenGL + 42
frame #2: 0x00000001084e54a3 QtOpenGL`QGLContext::~QGLContext() + 35
frame #3: 0x00000001084e55ce QtOpenGL`QGLContext::~QGLContext() + 14
frame #4: 0x00000001084e7fb8 QtOpenGL`QGLWidget::~QGLWidget() + 56
frame #5: 0x0000000104df623b ssr-binaural`ssr::QGUI::~QGUI() [inlined] ssr::QGUI::~QGUI(this=0x00007fc93bd27aa0) at qgui.cpp:213:2 [opt]
frame #6: 0x0000000104df6224 ssr-binaural`ssr::QGUI::~QGUI() [inlined] ssr::QGUI::~QGUI(this=0x00007fc93bd27aa0) at qgui.cpp:213 [opt]
frame #7: 0x0000000104df6224 …
```
> Leak the GUI

- .gitmodules
I'm not sure whether that's a good idea ...
I would like to use the BRIR files for the help patch of the upcoming BRS external for Pd.
But for now, I think we should not include the examples in the tarball nor in the macOS App Bundle nor installed in `/usr/local/share/ssr`, or should we?
It would be good to have the examples somewhere in the `$HOME` directory, but for that it's probably still easiest to download them as ZIP from https://github.com/SoundScapeRenderer/example-scenes.
> Add example-scenes as Git submodule

- AUTHORS
I think it's high time to add @umlaeute to the AUTHORS.
Even though he hasn't provided many commits to the SSR source code, his help in the issue tracker was extremely helpful over the years.
> Add IOhannes m zmölnig to AUTHORS

- flext/ssr_brs~.cpp
- flext/ssr_flext.h
The first problems was that the paths used in the Pd externals had extra quotes around them.
I didn't understand why, until I saw that the `<<` stream operator adds those quotes, see https://en.cppreference.com/w/cpp/filesystem/path/operator_ltltgtgt!
The solution is to simply convert the paths to strings first.
I'm still not sure whether "native" or "generic" paths should be used here, I guess we'll see once this is used on Windows.
The second problem was that the directory of the Pd patch (a.k.a. "canvas dir") was initialized too late.
I thought I'd have to refactor the whole thing to solve this, but actually, it was quite a simple and localized fix.
> Two fixes for the Pd externals

- .github/workflows/pd-externals.yml
This avoids a few warnings on the "Actions" page.
> CI: upgrade to actions/download-artifact@v3

- .circleci/config.yml
I found out that the auto-generated tarball contained a file named correctly like the PDF manual, but it had zero size.
The reason was, quite simply, that the PDF manual has to be built first, and only then can it  be included in the tarball.
> CircleCI: build PDF manual before tarball

- configure.ac
This avoids a few warnings when running `./autogen.sh`
> autoupdate

- src/pathtools.h
This is the same problem as in #281.
The problem happens when specifying a WFS filter or HRIR file with a relative path in a config file, just like it's done in `data/ssr.conf.local`.
> Avoid quotes when converting paths to strings

- browser-gui/Makefile.am
- configure.ac
- man/Makefile.am
In the past, I have made sure that the tarball contains the manpages and the browser-gui files, but today I found out that this is quite useless, because those files are not used when building the SSR from the tarball!
With the changes in this PR, it hopefully works now.
> configure: check for pre-built manpages and browser-gui resources

- .github/workflows/main.yml
- ci/build-deps-macos.sh
- doc/manual/building-from-source.rst
- doc/manual/conf.py
`websocketpp` is now available with `brew`, so we don't need to build it from source anymore.
And I clarified the installation and (un)linking of `qt@5`.
Rendered HTML page: https://output.circle-artifacts.com/output/job/3d231f34-bdac-48ac-b404-a44e00e750b2/artifacts/0/manual/building-from-source.html#dependencies
> Update macOS instructions

- configure.ac
This hopefully fixes the check for pre-generated browser GUI files.
> configure: fix checking for browser GUI files

- .readthedocs.yml
- doc/manual/renderers.rst
Using a letter followed by a dot seems to lead to strange formatting (the line is turned into an ordered list): https://ssr.readthedocs.io/en/latest/renderers.html#spors2011
Also, all other references have the full first names.
> Manual: use unabbreviated first names in Spors2011 reference

- .circleci/config.yml
This can be used whenever the SSR formula in https://github.com/SoundScapeRenderer/homebrew-ssr is updated.
And I guess it would be good style to provide it with our downloads in https://bitbucket.org/spatialaudio/ssr/downloads/.
> CircleCI: generate SHA256 hash for tarball

- .circleci/config.yml
TBH, I don't think that anybody is reading those docs anyway, right?
This would reduce the CI time significantly. Building the docs only takes about 20 seconds, but uploading hundreds of HTML files takes 2.5 minutes.
If needed, they can be built locally with `make doc`.
The HTML version of the user manual is still built, but this is no problem because it's much faster (a few seconds).
> CircleCI: Don't build Doxygen docs

- src/controller.h
As suggested in #323, this shows the renderer type in the "about" string:
```
___     
/  ___   
___/  /  ___ 
___/  /    SSR (SoundScape Renderer) x.y.z
/     renderer type: BinauralRenderer
Website: <http://spatialaudio.net/ssr/>
Contact: <ssr@spatialaudio.net>
...
```
> Show renderer type in "about" string

- src/configuration.cpp
... otherwise, SSR crashes with a misleading error message if a second instance is started (because of the specified port being unavailable).
> Switch off websocket server by default

- doc/manual/index.rst
I thought that the full TOC on the first page might be a bit overwhelming?
And I'm not sure if it helps to give some usage instructions ...
> Manual: hide TOC by default on index page, add usage instructions

- data/ssr
#325 has broken CircleCI, because `make distcheck` seems to check the output of `ssr --help` and `ssr --version`.
> Fix exit code of ssr --help/--version, print to stdout

- flext/Makefile
I have just realized that the `assert()` calls are enabled for the Pd externals.
I first thought that optimizations are disabled, but that's not the case.
We only need to define `NDEBUG` to disable `assert()`s.
> Pd externals: build with NDEBUG

- src/gui/quserinterface.cpp
There was an if statement on whether there was enough space for the timeline to fit. It was always untrue so that the timeline stayed hidden. Nowadays, we fix the size of the transport panel in pixels which means that the if statement if not required. I did not delete it but commented it out so that we can bring it back at some point.
> Make timeline visible

- .github/workflows/main.yml
GCC 8 made problems in #337, so let's get rid of it!
That's the underlying problem in case somebody is interested: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90050
> CI: drop support for gcc 8

- mex/ssr_mex.h
- src/controller.h
- src/legacy_network/commandparser.cpp
A few years ago, I changed a few underscores to hyphens: c06e61706a3c60e9966069992ec23999445e2c9e
It turns out that I was a bit over-eager and also changed an XML attribute which I shouldn't have changed.
This fixes a part of #345.
> Use properties_file instead of properties-file when saving ASD

- .github/workflows/main.yml
- src/configuration.cpp
- src/controller.h
- src/gui/qgui.cpp
- src/pathtools.h
Introduce `get_home_dir()` and `normalize_path()`.
> Extend pathtools cross-platform

- doc/manual/installation.rst
I don't think that `jack` has to be installed manually in this case, right?
> DOC: update instructions for the brew package

- doc/manual/browser-gui.rst
Previously, the websocket server has been started by default, but now it has to be done explicitly.
> DOC: --websocket-server is now required for the browser GUI

- configure.ac
Currently, this has no effect, because `$EXEEXT` is empty for Linux and macOS.
However, this might come in handy for Windows, see #351 and #352.
> configure.ac: add $EXEEXT

- doc/manual/browser-gui.rst
- doc/manual/operation.rst
- doc/manual/renderers.rst
- src/gui/qopenglplotter.cpp
- src/trackerpolhemus.cpp
- src/trackerpolhemus.h
Relates to #140.
I tested this for the binaural renderer, and I can confirm that this is now as we discussed it. As a byproduct, this PR enables 3D head tracking with Polhemus trackers. 
But I'm not sure about the other renderers. Please test this. I have the feeling that this 
https://github.com/JensAhrens/ssr/blob/dd1d54491184b9aad4b6d3e53e08c1caa049db97/src/gui/qopenglplotter.cpp#L456-L457
needs to be removed because it is already carried out here:
https://github.com/JensAhrens/ssr/blob/dd1d54491184b9aad4b6d3e53e08c1caa049db97/src/gui/qopenglplotter.cpp#L364-L368
> Fix reference offset in GUI and add 3D support for Polhemus tracker

- .circleci/config.yml
- .github/workflows/main.yml
- configure.ac
- src/Makefile.am
- src/configuration.cpp
- src/controller.h
- src/dynamic_scene.h
- src/rendererbase.h
This is an incomplete implementation of the still very incomplete dynamic ASDF.
(Incomplete) documentation of the ASDF can be found at https://audioscenedescriptionformat.readthedocs.io/
To compile this, the ASDF library has to be installed, see https://github.com/AudioSceneDescriptionFormat/asdf-rust#building-the-c-api
The new ASDF library does *not* depend on Ecasound, therefore it might even be possible to compile it on Windows (but I didn't try).
Support for the dynamic ASDF is completely optional, it can be disabled with
./configure --disable-dynamic-asdf
> Support for dynamic ASDF scenes

- doc/manual/network-websocket.rst
Some time ago we have disabled the WebSocket interface by default, so we should probably mention how to enable it again.
> DOC: show how to enable the WebSocket interface

- doc/manual/building-from-source.rst
With our new `libmysofa` package for `brew`, there should be no need for manual compilation anyway.
> DOC: remove mention of build-deps-macos.sh, which has been removed

- configure.ac
- src/gui/quserinterface.cpp
I saw a lot of deprecation warnings when building and figured that some of them could be eliminated. I then noticed that all the `sprintf()` deprecations come from the submodule libraries. Hence, only one warning is prevented (`delta`), and one kind of warning that occurs many times is silenced (OpenGL). The latter may be a warning exclusive to macOS (not sure).
I have quickly verified the `QWheelEvent` change (`delta`). The zoom of an `ssr-binaural` scene worked for me as before (tested on macOS). 
To see the other builds succeed, I have temporarily disabled the two failing macOS CI build configurations, as mentioned in https://github.com/SoundScapeRenderer/ssr/issues/380. These should not be merged and treated separately.
> Remove code deprecations

- .github/workflows/pd-externals.yml
... to clarify that 32-bit is not supported.
This has been recommended on the Pd mailing list: https://lists.puredata.info/pipermail/pd-list/2023-12/132848.html
> CI, PD externals, Windows: use m_amd64 extension

- .github/workflows/main.yml
- doc/manual/building-from-source.rst
I think this is cleaner to temporarily link Qt5 from homebrew when Qt6 is also installed, with the main reason that the brew link configuration does not need to be corrected and reverted to Qt6 after building.
The GitHub Actions currently fail due to an outdated macOS+Xcode configuration as described in https://github.com/SoundScapeRenderer/ssr/issues/380. I've manually rerun a newer configuration, which was built successfully.
> Improve Qt5 linking on macOS

- .github/workflows/main.yml
See https://github.com/actions/runner-images/issues/4020.
The work-around is based on https://github.com/TeamForbiddenLLC/warfork-qfusion/pull/325.
This problem doesn't seem to to appear with `macos-14`.
> CI: fix Python installation with brew

- .github/workflows/main.yml
This is stacked on top of #383.
> CI: add Xcode 15.1

- .github/workflows/main.yml
> CI: add macos-14

- .github/workflows/main.yml
Mostly updating to the latest available versions and adding `macos-15` which should be available now (configurations based on https://github.com/actions/runner-images/tree/main/images/macos).  Lets see how it goes.
If you want to limit the number of jobs, we could get rid of `macos-13, Xcode_14.3.1` as it is maybe obsolete.
> CI: Update macOS matrix with latest versions

- .github/workflows/pd-externals.yml
I'm not sure if `ucrt64` is the best choice, but it seems to be recommended nowadays.
> CI MSYS2: choose ucrt64 and use pacboy
